### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by Ph1b**
* Improved code quality
* Fixed minor bugs
* Added german translation
* Added confirmation dialog on resetting the game
* Updated dependencies

### CODE REVIEW

**Comment by tpcstld** [comment]
Woah thanks! I'll review this later today!

**Comment by tpcstld** [comment]
Also, out of curiosity, which phones have you tested this on, if any?

**Comment by Ph1b** [comment]
Just the 'edges', meaning 2.3.7 on Genymotion and 5.0.2 on Moto E.

**Comment by tpcstld** [comment]
Great! That's perfectly fine, thanks so much. Again, I'll look into this tonight, when I have free time.

**Comment by tpcstld** [comment]
Can you make the dialog only show if the game has not finished?

**Comment by Ph1b** [comment]
Here we go.

**Comment by tpcstld** [comment]
Looks good! I'm going to test this myself tonight, and if I find no problems I'll merge it (:

**Comment by tpcstld** [comment]
Some more changes:

There seems to be a bar at the top of my screen, can you please remove it?
Can you please change the text in the dialog from "continue" to "cancel"? So it's now "cancel" or "reset".

Thanks a lot!

**Comment by tpcstld** [comment]
Ok, one final change, and then I'll merge the code:

Change "Are you sure you want to reset the game?" to "Are you sure you **wish** to reset the game?"

Thanks for everything (:

**Comment by Ph1b** [comment]
Why dont you make these tiny changes yourself, I cannot open up my IDE each time ;-)

**Comment by tpcstld** [comment]
Haha, sorry. Ok I'll make these changes myself from now on (:

Would you like to be credited for these changes on the play store? If so do you want to use your real name or some other name? :D

**Comment by tpcstld** [comment]
Thanks for the changes (:

**Comment by Ph1b** [comment]
No problem! My real name is fine. I dont have a problem with making changes, but I think its easyest if you make small changes (like typos) by yourself. Anyway, great game :)

**Pull request merged**
