### PR TITLE
Add Spanish, fix Portugese translation, and update readme

### PR DESCRIPTION
**Pull request by schwartzadev**
* The portugal translation's name was `values-pt-PT`, while it should be `values-pt-rPT`
* The readme now has real markdown links instead of urls. I added some general information about contributing as well. It would be great if we could expand on this list.

Let me know if there is anything else that needs work!

### CODE REVIEW

**Comment by schwartzadev** [comment]
ping

**Comment by tpcstld** [comment]
Thank you so much! I missed these PRs when I was busy over the holidays X_X.

I'll merge this. I was thinking about creating a CONTRIBUTORS file as well to document and credit all the people who helped translated and improve this too :)

**Comment by schwartzadev** [comment]
Yeah of course!

**Comment by tpcstld** [comment]
I just made the file, and added your username, let me know if you have a different alias you want to go by (probably easier than making a PR).

**Comment by schwartzadev** [comment]
No, thanks so much though. Maybe you could link to my account though?

**Pull request merged**
